version: '3.8'

services:
  API:
    container_name: scrum-server
    build: ./api
    command: npm run server
    image: node:16-alpine

    ports: 
      - 3000:3000
    volumes:
      - .:/app

  postgres:
      container_name: scrum-database
      image: postgres:14
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}

      ports:
        - 5432:5432