version: '3.8'

name: Scrum-app
services:
  client:
    image: ${DOCKER_REGISTRY-}cliente-scrum-app
    container_name: scrum-client
    build: 
      context: ./client
      dockerfile: .Dockerfile
      target: develop-stage
    volumes:
      - ./client:/src
    ports:
      - 8080:8080
    command:
      quasar dev -m spa

  api:
    container_name: scrum-api
    build: ./api
    command: npm run server
    image: node:16-alpine

    ports: 
      - 3000:3000
    volumes:
      - ./api:/app

  postgres_db:
      container_name: scrum-database
      image: postgres:14
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}

      ports:
        - 5432:5432