version: '3.8'

name: Scrum-app
services:
  client:
    image: ${DOCKER_REGISTRY-}cliente-scrum-app
    container_name: scrum-client
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: develop-stage
    volumes:
      - ./client:/src
    ports:
      - 8080:8080
    command:
      quasar dev -m spa

  api:
    container_name: scrum-api
    image: node:16-alpine
    command: sh -c "npm install && npm run server"
    depends_on:
      - postgres_db
    ports: 
      - 3000:3000
    volumes:
      - ./api:/app

  postgres_db:
      container_name: scrum-database
      image: postgres:14
      environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=user
        - POSTGRES_DB=postgres_db

      ports:
        - 5432:5432