version: '3.8'

name: Scrum-app
services:
  api:
    container_name: scrum-api
    command: sh -c "npm i && npm run server"
    image: node:16-alpine
    depends_on:
      - postgres_db
    ports: 
      - 3000:3000
    volumes:
      - .:/app

  postgres_db:
      container_name: scrum-database
      image: postgres:14
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}

      ports:
        - 5432:5432